import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GoHome from "./go-home";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className=" flex mb-20 gap-10">
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/about">About</a>
						</li>
					</ul>
				</nav>
				{children}
				<GoHome />
			</body>
		</html>
	);
}
